services:
  - type: web
    name: store-api
    env: node
    region: frankfurt
    plan: free
    autoDeploy: true
    buildCommand: "npm ci"
    startCommand: "npm start"
    healthCheckPath: "/healthz"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: store-db
          property: connectionString
      - key: JWT_SECRET
        value: change-me-in-dashboard
      - key: SESSION_SECRET
        value: change-me-in-dashboard
      - key: STRIPE_SECRET_KEY
        value: change-me-in-dashboard
      - key: CLIENT_URLS
        value: "http://localhost:5173"
      - key: CLIENT_URL
        value: "http://localhost:5173"
      - key: STRIPE_CURRENCY
        value: gbp
      - key: SWAGGER_ENABLED
        value: "true"
      - key: SESSION_TTL_MS
        value: "604800000"

databases:
  - name: store-db
    plan: free
    region: frankfurt
    databaseName: store_db
    user: store_user
